### ISSUE TITLE
Similar Challenges

### ISSUE THREAD

**Issue by RealJammy** [TheWinRaRs/Writeups#3]
If challenges are similar, i.e ws1,2 and 3, do we combine them under one writeup?

**Comment by rak1507** [comment]
No.

**Comment by RealJammy** [comment]
Why?

**Comment by rak1507** [comment]
Different challenges innit

**Comment by RealJammy** [comment]
but if they're all basically use wireshark lol, then they should be under one thing.
For example, if a skid is learning how to use WS, then having them all under one roof would show the gradual difficulty increase of the challs

**Comment by rak1507** [comment]
What about one folder with the pcap and 3 writeups?

**Comment by RealJammy** [comment]
True, we should do that now, could you make one in angstrom for me?

**Comment by James-261** [comment]
Different writeup for each all in one folder with pcap.

**Comment by TheWinRaRs** [comment]
One folder with the pcap and 3 writeups.
